server:
  port: 8080

logging:
  level:
    org.springframework.cache: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener
    username: user1
    password: admin

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      indent-output: true